### ISSUE TITLE
Language switcher inside the docs (/docs/v0.1.0) is broken :(

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#125]
Looks like when I click on the language switcher on http://googlecloudplatform.github.io/gcloud-ruby/docs/v0.1.0/, nothing happens.

Could we make that go back to working?

**Comment by blowmage** [comment]
Oops. Yeah, I'll get this fixed real quick.

This does highlight one of the problems with keeping the rdoc template in this repo. If we have a problem like this that needs to be applied to older docs, the template needs to be backported to those tags, because the template is local. I think a better solution is to put the template in an external repo/gem so we can fix problems like this without moving tags.

**Comment by jgeewax** [comment]
Hmm -- looping in the gcloud-node folks...

@ryanseys @stephenplusplus : How do we handle generating docs for older versions ? Do we have any issues with a singleton template (master) running against older versions ?

**Comment by stephenplusplus** [comment]
Nope, our same template can handle any version given, as long as we log when modules were changed/added/deleted in this file: https://github.com/GoogleCloudPlatform/gcloud-node/blob/bc2b57ce4e2d84a8d2ff722d677ddfe681fc8d00/docs/site/components/docs/docs-values.js#L111

Unfortunately I don't have much experience with Ruby or the system here, so I can't be much more help. In fact, I'm not even sure I've provided a helpful answer above!
