### ISSUE TITLE
Is there a way to globally configure Gcloud and have that configuration trickle down?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-ruby#137]
The examples I see are things like

```ruby
require 'gcloud/storage'

storage = Gcloud.storage
bucket = storage.find_bucket "my-bucket"
```

If I wanted to configure this, I have to configure each item individually:

```ruby
require 'gcloud/storage'
require 'gcloud/datastore'

storage = Gcloud.storage "my-project-id"
datastore = Gcloud.datastore "my-project-id"
```

Is there a way to configure things at the Gcloud level? that is:

```ruby
require 'gcloud'

gcloud = Gcloud "my-project-id"
storage = gcloud.storage
dataster = gcloud.datastore
```

**Comment by blowmage** [comment]
An issue I see with making all services available on the initial require is that gcloud could be loading many, many services that are never used. What happens when gcloud supports Datastore, Storage, Cloud SQL, BigQuery, Pub/Sub, Compute Engine, DNS, Load Balancing, Monitoring, Logging, etc? Do we really want to load all that if the user only wants to make calls to Storage? If the services are scoped to a require then the user gets to control which code is loaded, which should be beneficial in a production environment.

That's my thinking so far, but I'm happy to change those thoughts. :)

**Comment by jgeewax** [comment]
Maybe you can help me understand how much overhead it is to "load" all these service.

In Python and Node it's not that big of a deal to import the module.

The idea would be that someone doing this would be using **at least 2** of the services -- because the whole point is that you want to configure all of your stuff one time.

Is it reasonable to at least make this *possible*, while saying "if you're only using one service, this is dumb and will be slower..." ?

**Comment by blowmage** [comment]
My concern about loading services is about dependencies. Datastore requires the beefcake library for protobuf, while Storage requires the mime-types and digest-crc libraries for dealing with files. IMO gcloud shouldn't load those dependencies unless they are needed. (And shouldn't load `Gcloud::Datastore` or `Gcloud::Storage` namespaces until needed either.) The easiest, most idiomatic way to manage dependencies is to put them behind a require. That said, we can make your proposed API work, but we want to make sure we aren't loading things before they are needed. I'll give it some thought.
