### ISSUE TITLE
Certificate verify failed (Faraday:SSLError)

### ISSUE THREAD

**Issue by VincentVanGoat** [GoogleCloudPlatform/gcloud-ruby#218]
I got this error while trying to create a new file in my bucket.

```
c:/Ruby21-x64/lib/ruby/2.1.0/net/http.rb:920:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
        from c:/Ruby21-x64/lib/ruby/2.1.0/net/http.rb:920:in `block in connect'
        from c:/Ruby21-x64/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
        from c:/Ruby21-x64/lib/ruby/2.1.0/net/http.rb:920:in `connect'
        from c:/Ruby21-x64/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
        from c:/Ruby21-x64/lib/ruby/2.1.0/net/http.rb:852:in `start'
        from c:/Ruby21-x64/lib/ruby/2.1.0/net/http.rb:1369:in `request'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/faraday-0.9.1/lib/faraday/request/url_encoded.rb:15:in `call'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/signet-0.6.1/lib/signet/oauth_2/client.rb:957:in `fetch_access_token'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/signet-0.6.1/lib/signet/oauth_2/client.rb:983:in `fetch_access_token!'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/gcloud-0.2.0/lib/gcloud/credentials.rb:55:in `initialize'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/gcloud-0.2.0/lib/gcloud/storage.rb:54:in `new'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/gcloud-0.2.0/lib/gcloud/storage.rb:54:in `storage'
        from c:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/gcloud-0.2.0/lib/gcloud.rb:115:in `storage'
        from storage-api-test.rb:5:in `<main>'
```

**Comment by VincentVanGoat** [comment]
the last line is:

from storage-api-test.rb:5:in '<main>'

**Comment by VincentVanGoat** [comment]
the last line is:

from storage-api-test.rb:5:in 'main'

The main is in tags but doesn't get displayed for some reason..

**Comment by blowmage** [comment]
Hi @VincentVanGoat, thanks for opening the issue! The problem you are having is due to how Ruby looks for the SSL certificates on your system. It looks like Ruby is unable to find a valid SSL cert that will work for connecting to the Google Cloud API. This is apparently a common problem with Ruby on Windows due to some changes in RubyGems and how Ruby uses SSL certificates. Unfortunately this is not something the gcloud gem can fix for you, you have to make some changes to your system.

First you should read Luis Lavena's gist on [SSL upgrades on rubygems.org and RubyInstaller versions](https://gist.github.com/luislavena/f064211759ee0f806c88). It covers the error you posted and details the steps to resolve it. This should solve the error you are having.

Here is some more information about Ruby and SSL certificates. Faraday has an entry on their wiki that explains [how to set up SSL certificates](https://github.com/lostisland/faraday/wiki/Setting-up-SSL-certificates). Unfortunately, that wiki does not explain how to do this for Windows.

One resource for setting up SSL certs on Windows for Ruby is [this Stack Overflow answer](http://stackoverflow.com/a/16134586/5627). Essentially, you need to acquire a known valid cert, either from the previous gist or the Stack overflow answer, and tell Ruby where it is by setting the path to the file in the `SSL_CERT_FILE` environment variable.

I hope all this is helpful. If not, let us know what behavior you are seeing and we'd be glad to remote pair with you to get your system configured properly.

**Comment by VincentVanGoat** [comment]
Thank you for your answer. The Stack Overflow answer does give a great method. It says that I'll have to find and download the cacert.pem into c:\railsinstaller\. I unfortunately could not find 'railsinstaller' anywhere on my computer. Where do I download the cancert.pem then?

**Comment by blowmage** [comment]
@VincentVanGoat The Stack Overflow answer instructs you to download the cert from http://curl.haxx.se/ca/cacert.pem and then you can put it anywhere on your system. The location is not important, as long as the location is stored in the `SSL_CERT_FILE` environment variable.

**Comment by VincentVanGoat** [comment]
Thanks! This issue was fixed.
