### ISSUE TITLE
BigQuery Table#id

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#227]
I would like to ask a table what its ID is. It would be useful for using the fully namespaced table name in queries.

```ruby
dataset.query "SELECT name, age FROM [#{table.id}]"
```

**Comment by quartzmo** [comment]
An added convenience would be for `Table#id` to detect dashes in the project name, and supply the enclosing square brackets if needed.

>Note: if your project name includes a dash, you must surround the entire table reference with brackets, as in [my-dashed-project:dataset1.tableName].

from: https://cloud.google.com/bigquery/query-reference#from

So that you can then write the following without worrying about whether you need the square brackets. (Most projects will need them, I think.)

```
dataset.query "SELECT name, age FROM [#{table.id}]"
```
