### ISSUE TITLE
Gcloud::Datastore::PropertyError: A property of type NilClass is not supported.

### ISSUE THREAD

**Issue by enzomd** [GoogleCloudPlatform/gcloud-ruby#259]
```
Gcloud::Datastore::PropertyError: A property of type NilClass is not supported.
from /usr/local/bundle/bundler/gems/gcloud-ruby-1aa4fc7dcf89/lib/gcloud/datastore/properties.rb:102:in `ensure_value_type'
```
This happens with values that are null.

**Comment by jgeewax** [comment]
Do you have some sample code that raises the error?

**Comment by enzomd** [comment]
To replicate:
Set values to null in the datastore UI:
![86014afd-567f-4f8c-8f31-51bce938ccf0](https://cloud.githubusercontent.com/assets/11319476/9568905/ab749730-4f50-11e5-9639-2f2f9b488ba3.png)

Read them:
`dataset.find("Kind", "Key")`

**Comment by jgeewax** [comment]
Awesome -- thanks -- we'll dig in :)

**Comment by blowmage** [comment]
@enzomd Thanks for submitting the issue. I'll take a look at it. Let me know if you have a reproduction. Thanks again.

**Comment by blowmage** [comment]
@enzomd I think we've identified a fix for this with #260. We will include this in the 0.3.1 release that is planned for this week. 

It looks like you are using Bundler to reference the GitHub repo instead of using the gem. Can you update to the latest commit (`$ bundle update gcloud`) and let us know if this change has fixed the error you were seeing?

**Comment by enzomd** [comment]
@blowmage @jgeewax thank you its working now

**Comment by blowmage** [comment]
:metal:
