### ISSUE TITLE
Manage File Metadata

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#278]
Support management of a file's [metadata](https://cloud.google.com/storage/docs/gsutil/addlhelp/WorkingWithObjectMetadata#custom-metadata). _This issue is rudimentary, needs details to be filled in as we learn more._

- [x] Allow setting metadata during file creation:

```ruby
bucket.create_file "hello.txt", metadata: { title: "Hello world!" }
```

- [x] Allow getting values using the `metadata` method.

```ruby
file.metadata["title"] #=> "Hello world!"
```

- [x] Allow setting a new value using a setter method.

```ruby
file.metadata = { title: "Goodbye cruel world!" }
```

Calling this method makes an API call to update the value. A caveat is that this won't update the API:

```ruby
file.metadata["title"] = "Goodbye cruel world!" # updates local hash, does not make an API call.
```

Calling this method inside an update block should update the API:

```ruby
file.update do |f|
  f.metadata["title"] = "Goodbye cruel world!"
end
```

**Comment by quartzmo** [comment]
@blowmage For returned hashes like this (everywhere in gcloud eventually, Bucket#cors for example), I am in favor of [freezing](http://ruby-doc.org/core-2.2.3/Object.html#method-i-freeze) the return value so that modification is not possible. There is no sense in taking the chance that a user is misled into thinking a remote update was made.

> Calling this method makes an API call to update the value. A caveat is that this won't update the API:

What's your feeling on this?

**Comment by blowmage** [comment]
I agree with freezing.

**Comment by quartzmo** [comment]
Thanks @blowmage, will do.

**Comment by quartzmo** [comment]
Modifying the hash without sending a request to the service won't be possible. The returned hash will be frozen.
