### ISSUE TITLE
Should we publish a separate module (gem) for each Google Cloud service?

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#341]
This is the gcloud-ruby specific discussion of the broader conversation in gcloud-common, [#30, Should separate APIs be separately installable?](https://github.com/GoogleCloudPlatform/gcloud-common/issues/30). See also @jgeewax's [comment in gcloud-node #91](https://github.com/GoogleCloudPlatform/gcloud-node/issues/91#issuecomment-138522547).

**Comment by blowmage** [comment]
This has been discussed before and the current monolithic direction was chosen.

My opinion is that they should be separate. We can manage versions independently, and release hotfixes for one service gem without requiring the other service gems to be updated. I think we should follow what rspec does and have the main gcloud gem have dependencies on all the service gems. And we should have a gcloud-core gem that contains shared infrastructure like Error and Backoff.

gcloud -> gcloud-datastore, gcloud-storage, gcloud-pubsub
gcloud-datastore -> gcloud-core, beefcake (protobuf lib)
gcloud-storage -> gcloud-core
gcloud-pubsub -> gcloud-core

The current behavior would remain, you require gcloud and you get all the services available. But, if you wanted to only use Storage you could depend on gcloud-storage and require gcloud/storage and only have that code. The caveat for this is that right now the unused services aren't loaded and memory isn't used, but the dependencies may be loaded if you are using Bundler and configured it to load everything. This approach would also make development and documentation more difficult since it would span several projects.

**Comment by blowmage** [comment]
![monolith](https://cloud.githubusercontent.com/assets/730/10199595/b46889e8-675e-11e5-9cd9-f859440d3449.png)
