### ISSUE TITLE
Having to choose between methods for retrieving a Topic or Subscription is confusing

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#400]
In #393, @jeffmendoza wrote:

> This library allows a lot of flexibility

I share that impression, and in particular I was confused by the presence of two methods for retrieving topics and two for retrieving subscriptions:

* [Project#get_topic](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/v0.4.1/lib/gcloud/pubsub/project.rb#L103)
* [Project#topic](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/v0.4.1/lib/gcloud/pubsub/project.rb#L173)

and

* [Project#get_subscription](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/v0.4.1/lib/gcloud/pubsub/project.rb#L298)
* [Project#subscription](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/v0.4.1/lib/gcloud/pubsub/project.rb#L329)

The method names do little to suggest a distinction, so I looked at the docs, [which state](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/v0.4.1/lib/gcloud/pubsub/project.rb#L117-L118):

> The difference between this method and Project#get_topic is that this method does not make an API call to Pub/Sub to verify the topic exists.

To me the behavior of "avoiding the API call to verify the Topic exists" feels like it should be an option to `Project#get_topic`, not a separate method.

Digging into the code, however, I found a rather involved mechanism for lazy loading. In the case of Topic, does this mechanism serve any goal other than just letting the user publish a message without needlessly retrieving a topic? If not, it seems to me that much internal complexity (and potential user confusion about state) could be avoided with a method that simply accepts the topic name and message:

```ruby
pubsub = gcloud.pubsub
msg = pubsub.publish  "existing-topic", "This is the first API call to Pub/Sub."
```

In my opinion, this simple design makes it very clear that the Topic is not being retrieved, and that "this method does not make an API call to Pub/Sub to verify the topic exists."

Clearly there could be more to this lazy loading than I was able to find on my own, so please inform me!

**Comment by blowmage** [comment]
Much of the "lazy object" is specific to optimizing the `publish` use case. Performance it increased because gcloud is able to publish a message on a topic without first making the API call to retrieve the topic.

```ruby
gcloud.pubsub.topic("my-topic").publish("my message") # 1 API call made
```

During initial development I proposed what you are proposing, a `publish` method at a higher level, but this was rejected at the time.

```ruby
gcloud.pubsub.publish("my-topic", "my message") # 1 API call made
```

I find the second example less confusing. I think it would help with conceptual overhead the current design has as it doesn't introduce an additional state to the topic objects.

**Comment by blowmage** [comment]
@stephenplusplus @tmatsuo Thoughts on the ^ proposed solution?

**Comment by tmatsuo** [comment]
I like the simple solution of having 
```ruby
gcloud.pubsub.publish("my-topic", "my message") # 1 API call made
```
The question here is what is the purpose of having topic object at all? Is it really useful?

**Comment by blowmage** [comment]
Topic is still useful for listing the subscriptions that are tracking a topic, as well as managing the IAM policy and testing the IAM permissions.

**Comment by quartzmo** [comment]
The [REST representation of Topic](https://cloud.google.com/pubsub/reference/rest/v1/projects.topics#Topic) is its name and nothing more. So if you know the name, apparently there's no sense in loading it, other than to verify existence.

**Comment by blowmage** [comment]
I've been moving some things around in #402, and right now the difference between `#topic` and `#get_topic`, and between `#subscription` and `#get_subscription` has been removed. The methods are now the same (one is an alias of the other) and always return a looked up record. Also, `Project#publish` and `Project#subscribe` have been added to perform the single API action with optional `autocreate`.

We may decide to allow these methods to skip lookup and return a "lazy" object in the future, but that will be implemented as a new optional parameter to those methods instead of maintaining two different methods. One reason for this is because gcloud offers many ways to pull messages from a Subscription, and so having a way to skip lookup would be useful in those cases. Or to get/set the IAM policy without also performing the initial lookup, which would be useful for checking permissions on a topic/subscription before attempting to exercise the permissions by retrieving the resource.
