### ISSUE TITLE
Setting location when creating a dataset

### ISSUE THREAD

**Issue by gramos74** [GoogleCloudPlatform/gcloud-ruby#571]
Right now we can retrieve the location of a dataset but are not able to set it when we create a dataset.
Could be possible to add it as an option ?

**Comment by quartzmo** [comment]
@gramos74 The current policy, unless I'm mistaken, is not to add features/options to gcloud-ruby that are marked `[Experimental]`, like [BigQuery Dataset location](https://cloud.google.com/bigquery/docs/reference/v2/datasets#location), in order to avoid having to deprecate and remove them if they are discontinued. That said, we already support reading the value, as you noted, which is now inconsistent.

Also, the section [Choosing a location](https://cloud.google.com/bigquery/docs/managing_jobs_datasets_projects#dataset-location) now appears in the official API documentation. How urgently do you need to set the non-default `EU` value? Or were you just curious? We may be able to investigate whether the `Experimental` status can be removed.

**Comment by gramos74** [comment]
In fact, choosing a location is not only available via API, it is also a option when you create manually a dataset in the BigQuery web console.

For me this option is not really critical because right now I'm using directly the Google API Client in order to create the datasets in the EU. But, I would like to remove this workaround asap.

if at any moment you think that makes sense support this option I would be happy of contributing.

**Comment by blowmage** [comment]
We are not entirely consistent with how we have supported experimental features. We have some experimental features in the current API, but we also have been told to not support experimental features so we don't have to make breaking API changes if they are removed. Its complicated.

I'd support adding `location` to `Project#create_dataset` because 1) we already support `Dataset#location`, and 2) we already support `default_timeout`, which is also marked as experimental. I think this would be a logical change.

**Comment by quartzmo** [comment]
I am also in favor of adding the ability to write dataset location. @gramos74 Do you want to create a pull request for this? I can help if you run into any issues.

**Comment by quartzmo** [comment]
@gramos74 There may be a point release sooner than anticipated, so I am going to do a PR now to add `location` to `Project#create_dataset`. Thanks for reporting this inconsistency!

**Comment by blowmage** [comment]
This fix included in the [0.6.2 release](https://github.com/GoogleCloudPlatform/gcloud-ruby/releases/tag/v0.6.2).
