### ISSUE TITLE
Add IAM as a Service

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/gcloud-ruby#592]
Before GRPC each Service exposed IAM calls. Now that we have moved to GRPC we can expose IAM as an independant service. This will allow more flexibility for advanced users. This will also allow for users to configure IAM on services not yet implemented in gcloud-ruby.

**Comment by quartzmo** [comment]
I’m not sure that using gRPC is an option. Even though in our Pub/Sub service we appear to be using top-level IAM resources (`Google::Iam::V1::IAMPolicy`, etc), when I try to use these same stubs against `iam.googleapis.com` instead of  `pubsub.googleapis.com`, I get the following error:

`12:GRPC target method is not implemented.`

**Comment by quartzmo** [comment]
Placing this issue on hold, since the original opportunity (gRPC-based IAM) does not appear to exist. If anyone feels we should proceed with an implementation for the [Rest API](https://cloud.google.com/iam/reference/rest/), feel free to remove the label.
