### ISSUE TITLE
Blob values created as ndb JsonProperty return as Base64 decoded

### ISSUE THREAD

**Issue by bmclean** [GoogleCloudPlatform/gcloud-ruby#666]
We have entities in our datastore that were previously created using the ndb [JsonProperty](https://cloud.google.com/appengine/docs/python/ndb/entity-property-reference). For those entities the Gcloud::Datastore::Proto::Value `blob_value` doesn't seem to be returned as Base64 encoded. For example, adding this debugging to Proto.[from_proto_value](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/f944f6c4cd8cbff6f2a6432999ac36288ad5a89f/lib/gcloud/datastore/proto.rb#L58):

    elsif !proto_value.blob_value.nil?
      puts "*" * 40
      puts proto_value.blob_value
      return StringIO.new(Base64.decode64(proto_value.blob_value))  

returns this:

    ****************************************
    {"transaction": {"crc": 2325900754, "entity_version": 1225}, ...

Which is very strange, as when I look at the value for those entities using the cloud.google.com DataStore Viewer they are encoded. Why do these properties return already decoded?

Should we test that contents of `blob_value` are in fact base64 encoded before attempting to base64 decode?

Should we instead raise an exception if `blob_value` isn't Base64 encoded?

**Comment by blowmage** [comment]
@bmclean I've looked into this and 1) this is a problem, and 2) this is cloud-ruby's fault. When sending blob bytes over the wire to Datastore through the JSON API we are supposed to base 64 encode the data. So in gcloud-ruby we are currently base 64 encoding the data. But, the Google API Client that we use to connect to the service is also base 64 encoding the data, so in effect we are double encoding the data with base 64. This is why you cannot view blob bytes already in Datastore, since gcloud-ruby is performing a _double decode_ with base 64.

This is a terrible situation, but one that gcloud-ruby can address pretty quickly. Unfortunately, this means that all data stored in Datastore by gcoud-ruby 0.8.1 is base64 encoded, and we don't have any mechanism to correct this. You will have to determine which records are incorrect and base64 decode them once we release a fix.

**Comment by blowmage** [comment]
Wow, the issue number for this bug is appropriate...

**Comment by bmclean** [comment]
@blowmage I have not yet released 0.8.1 into production so we are ok.

**Comment by blowmage** [comment]
Not to get weird, but I could kiss you. I feel really awful for shipping this bug.

**Comment by quartzmo** [comment]
We just released [0.8.2](https://rubygems.org/gems/gcloud/versions/0.8.2) to fix this in 0.8.1 (see #667 for details.)
