### ISSUE TITLE
Order by __key__ desc its broken

### ISSUE THREAD

**Issue by vyper** [GoogleCloudPlatform/gcloud-ruby#694]
```ruby
dataset = Gcloud.datastore
query = dataset.query('TestUser').order('__key__', :desc) # :asc works
dataset.run query
Gcloud::FailedPreconditionError: 9:This query requires a composite index that is not defined.
	from ~/.rvm/gems/ruby-2.3.0@hanami/gems/gcloud-0.9.0/lib/gcloud/datastore/dataset.rb:406:in rescue in run
	from ~/.rvm/gems/ruby-2.3.0@hanami/gems/gcloud-0.9.0/lib/gcloud/datastore/dataset.rb:397:in run
```

In old version (0.8.2) this code was worked.

**Comment by blowmage** [comment]
Hi @vyper. Unfortunately this doesn't look like an issue in gcloud-ruby, this is behavior the of Datastore v1beta3. To illustrate, I will run a GQL query in the [Google Cloud console](https://console.cloud.google.com/datastore/entities/query/gql):

Here is the query without specifying `ASC` or `DESC`:

![sort](https://cloud.githubusercontent.com/assets/730/15235578/cf9807da-1879-11e6-928d-5f33d2617cfe.png)

Here is the query specifying `ASC`:

![sort-asc](https://cloud.githubusercontent.com/assets/730/15235595/0db2840a-187a-11e6-8237-39b14facd1f5.png)

Here is the query without specifying `DESC`:

![sort-desc](https://cloud.githubusercontent.com/assets/730/15235599/12691324-187a-11e6-9a18-2362efc4068a.png)

As you can see, sorting results by the key in descending order requires a composite index. Perhaps @pcostell can let us know if this is a regression or expected behavior?

**Comment by bmclean** [comment]
@blowmage I think this is expected behaviour. Cloud Datastore has always required indexes for queries with a sort order on keys in descending order. It is documented [here](https://cloud.google.com/datastore/docs/concepts/indexes#index_configuration).

**Comment by blowmage** [comment]
Thanks for the link!

**Comment by vyper** [comment]
Thank for help! (:
