### ISSUE TITLE
Logging is missing from the ReadMe

### ISSUE THREAD

**Issue by rok987** [GoogleCloudPlatform/gcloud-ruby#743]
It seems like we have a wrapper for the Logging API in Ruby. Therefore we should add the following to the ReadMe (just like for the other APIs):

- a link at the top to the Logging API section
- a Logging API section with links to the documentation
- an example

**Comment by quartzmo** [comment]
Is this what you mean? https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/master/README.md#logging

**Comment by blowmage** [comment]
The [list of services](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/master/README.md#ruby-api-client-library-for-google-cloud) at the top of the README is missing Logging, Translate, and Vision.

**Comment by rok987** [comment]
Correct! The Logging section looks good. And yes, the only thing missing is to add the full list of services at the top (the one @blowmage called out).

**Comment by quartzmo** [comment]
@rok987 @blowmage Thanks for reiterating the suggestion about the link at the top. (Sometimes I just need to read something twice!)

@blowmage I wonder if we should add a subsection to [RELEASING](https://github.com/GoogleCloudPlatform/gcloud-ruby/blob/master/RELEASING.md) about adding new services, because it's not good that we're missing the list at the top.

**Comment by blowmage** [comment]
As we add more and more services and move to individual gems I think we will have to rethink the layout and content of the README. I don't have any concrete ideas on exactly how it should change though.
