### ISSUE TITLE
Error loading full representation from list item

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/gcloud-ruby#780]
I get this error when calling some methods on `Table` instances returned by `Dataset#tables`:

```sh
NoMethodError: undefined method `creation_time' for #<Google::Apis::BigqueryV2::TableList::Table:0x007ff49c1f3ce8>
    /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/bigquery/table.rb:878:in `data_complete?'
    /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/bigquery/table.rb:868:in `ensure_full_data!'
    /Users/quartzmo/code/google/codez/gcloud-ruby/lib/gcloud/bigquery/table.rb:312:in `location'
```

The implementation of `data_complete?` in `Dataset`, `Table`, and `View` should be changed to test the presence of accesors with `respond_to?`. The current implementation is a remnant from when the gapi object was hash-like. Now the gapi objects for partial representations are actually different types, such as `TableList::Table`. They lack accessors for the missing data.

**Comment by blowmage** [comment]
So there are two different table classes, one with a minimal subset of data, and one with the full data. The object you have there is a [`Google::Apis::BigqueryV2::TableList::Table`](http://www.rubydoc.info/github/google/google-api-ruby-client/Google/Apis/BigqueryV2/TableList/Table), instead of a [`Google::Apis::BigqueryV2::Table`](http://www.rubydoc.info/github/google/google-api-ruby-client/Google/Apis/BigqueryV2/Table). The way we differentiated between the two before was checking if the `creation_time` value was there, but with the change to GAPI 0.9 we could check the object's class.

**Comment by quartzmo** [comment]
Sounds ok to me, I don't mind testing the class instead of relying on a duck-typing approach. Will do.
